### PR TITLE
Add `-Wundef` to compile options

### PR DESCRIPTION
**Pull request by big-r81**
Give a warning for undefined macros to prevent errors like #11.

### CODE REVIEW

**Comment by NelsonVides** [comment]
This PR looks good but I find weird that even with such added flag, CI is still green while the macro remains undefined 🤔

**Comment by big-r81** [comment]
Hey, I updated the PR. If there are undef warnings, treat them like errors. If #12 is merged, this PR should run through.

**Comment by NelsonVides** [comment]
> Hey, I updated the PR. If there are undef warnings, treat them like errors. If #12 is merged, this PR should run through.

#12 merged, wanna rebase this one? :)

**Review by NelsonVides — APPROVED** [review]
Excellent, thank you! 😄

**Comment by NelsonVides** [comment]
https://hex.pm/packages/fast_pbkdf2/1.0.6 new hex package published too 🔥

**Pull request merged**
